### ISSUE TITLE
run with docker compose

### ISSUE THREAD

**Issue by mstewart14** [ReceiptManager/receipt-parser-server#61]
tried the following (note, I'm running on amd64 so had to build it myself)
tried the following as a docker-compose.yml

services:
  receipt-parser-server:
    image: 76b8a403068d #had to build locally for amd64
    container_name: receipt-parser
    environment:
      - RECEIPT_PARSER_CONFIG_DIR="/config"
    volumes:
      - ./parser/data:/app/data
      - ./parser/config:/config
    ports:
      - 192.168.0.233:8721:8721
    restart: unless-stopped 

instantly starts restarting and never comes up all the way.
why is that? 
running the launcher script (correctly modified to refer to this image and the IP) works and I end up with a running container.  It's important for me for back-up and management purposes.  
any help or clues would be appreciated

**Comment by emcniece** [comment]
What do the container logs say?

Mine say this:
```
standard_init_linux.go:178: exec user process caused "exec format error"
standard_init_linux.go:178: exec user process caused "exec format error"
standard_init_linux.go:178: exec user process caused "exec format error"
standard_init_linux.go:178: exec user process caused "exec format error"
```

This indicates an architecture conflict, and it appears to be the case. The DockerHub image says:

```sh
$ docker inspect bf07f8de4f4a | grep Arch
        "Architecture": "arm64",
```

... and I'm trying to run it on:
```sh
$ docker info | grep Arch
Architecture: x86_64
```

This image needs to be built for multiple architectures - I'll try a manual build first, then will see if it can be PR'd.

**Comment by don-philipe** [comment]
By building the image during compose process I was able to run the server. For this to happen first I cloned the repository. Then I had to copy the `config.yml` file from the root directory into `config/`. Then I added the following code into a `docker-compose.yml`:

```yml
services:
  receipt-parser-server:
    build: .
    container_name: receipt-parser-server
    restart: unless-stopped
    ports:
      - 8721:8721
    environment:
      RECEIPT_PARSER_CONFIG_DIR: /config
    volumes:
      - ./data:/app/data
      - ./config:/config
```
Finally accessing the container under the URL `http://$IP:8721` revealed the API token.
